In [1]:
import pandas as pd

In [2]:
!pip install xlrd

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [9]:
url = r'C:\Users\julia\OneDrive\Documentos\Ironhack\GSAF5.csv'

shark_attack = pd.read_csv(
    url,
    encoding="latin1",
    sep=None,
    engine="python"
)

In [10]:
#show columns

shark_attack.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [11]:
#drop the columns we don't need

shark_attack = shark_attack.drop(
    columns=[
        'Source', 'pdf', 'href formula', 'href',
        'Case Number', 'Case Number.1', 'original order',
        'Unnamed: 21', 'Unnamed: 22'
    ]
)

In [12]:
#drop the rows older than 1975 (left 50 years)
shark_attack = shark_attack[shark_attack['Year'] > 1975]

In [13]:
shark_attack

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,Greg O'Neil,M,63,Body not recovered,Y,1015hrs,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,Unknown Male,M,?,Injuries to chest shoulder and back,N,1030hrs,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,Unknown Austrian Tourist,F,37,Serious injuries to right ankle,N,1730hrs,Unknown
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,Mel Ismail,M,50's,Foot lost in attack,N,0945hrs,Unknown
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,Wants to remain anonymous,M,24,Scrapes on inside of legs,N,1640hrs,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,12/jan/76,1976.0,Unprovoked,AUSTRALIA,Queensland,Harvey Bay,NaN,Marlene Evler,F,NaN,Survived,N,NaN,NaN
3996,11/jan/76,1976.0,Provoked,SOUTH AFRICA,Western Cape Province,Kalk Bay,Fishing for snoek & yellowtail,"7 m fishing boat Metoo, occupants: Nicky & Pau...",NaN,NaN,"Hooked shark leapt onboard & into fish well, w...",N,07h30,"White shark, 3 m [10']"
3997,08/jan/76,1976.0,Unprovoked,USA,Florida,"Off Fort Pierce, St Lucie County",Spearfishing / scuba diving,Hank Greenberg,M,25,Puncture wounds to head & neck,N,NaN,6' shark
3998,02/jan/76,1976.0,Unprovoked,NEW ZEALAND,North Island,"Te Kaha, East coast",Spearfishing,John Grainger Leith,M,NaN,FATAL,Y,13h00,Bronze whaler shark
3999,1976,1976.0,Unprovoked,USA,Hawaii,"Off Lahaina, Maui",Scuba diving,Danson Nakaima,M,NaN,"FATAL, lost consciousness at depth of 180'. La...",Y,NaN,NaN

In [15]:
# Select only the columns I want to clean
columns_to_clean = ["Country", "State", "Location", "Activity"]

shark_clean = shark_attack[columns_to_clean].copy()

In [16]:
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    211
dtype: int64

In [21]:
# Remove extra spaces
for column in columns_to_clean:
    shark_clean[column] = shark_clean[column].str.strip()
display(shark_clean.head())

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,USA,Hawaii,Honolulu,Surfing

In [22]:
# Replace empty strings with NaN
shark_clean = shark_clean.replace(r"^\s*$", pd.NA, regex=True)

In [23]:
# Standardize capitalization
shark_clean["Country"] = shark_clean["Country"].str.title()
shark_clean["State"] = shark_clean["State"].str.title()
shark_clean["Location"] = shark_clean["Location"].str.title()

In [24]:
# For Activity, remove extra spaces
shark_clean["Activity"] = shark_clean["Activity"].str.strip()

In [26]:
# Check missing values again
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    212
dtype: int64

In [28]:
# Check cleaned data
display(shark_clean.head(10))

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off The Coast Of Perce Le Bilbo Dive Site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,Usa,Hawaii,Honolulu,Surfing
5,Usa,Florida,New Smyrna Beach,Surfing
6,Usa,Florida,30 Miles Off Pensacola,Spearfishing
7,Usa,Massachusetts,Norton Point Edgartown Marthas Vinyard,Swimming
8,Usa,Hawaii,"Ala Moana Beach Park, Oahu",Surfing
9,Usa,Florida,Boca Grande (Island In The Keys),Wading on a sandbar